[package]
name = "blescan-motion"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "motion"
path = "src/motion.rs"

[dependencies]
blescan-domain = { path = "../blescan-domain" }
coremotion-rs = "0.0.2"

