[package]
name = "blescan-mote"
version = "0.0.0"
edition = "2024"

[dependencies]
blescan-domain = { path = "../blescan-domain" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"